version: '2.4'

services:
  db:
    image: mongo:4.0.17-xenial
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    restart: 'no'
    volumes:
      - db-data:/data/db:delegated
<<<<<<< HEAD
  depends_on:
    - redis
  env_file:
    .env
  redis:
    image: 'redis:alphine'
=======
  redis:
    image: 'redis'
>>>>>>> bf975328910ba9c8071cbb270c0d1857723b0e2e
    ports:
      - 6379:${REDIS_PORT}
volumes:
  db-data: