version: '2.4'

services:
  db:
    image: mongo:4.0.17-xenial
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    restart: 'no'
    volumes:
      - db-data:/data/db:delegated
  redis:
    image: 'redis'
    ports:
      - 6379:${REDIS_PORT}
volumes:
  db-data: